name: guess_word_game
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^3.1.0
  http: ^0.12.1
  connectivity: ^0.4.8+5
  flutter_secure_storage: ^3.3.3
  sqflite: ^1.3.0+1
  path: ^1.6.4
  firebase_admob: ^0.9.3+2
  device_info: ^0.4.2+3
  flutter_gifimage: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - language/
    - images/
    - assets/data.json
  fonts:
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun-Regular.ttf
    - family: Sarabun-SemiBold
      fonts:
        - asset: fonts/Sarabun-SemiBold.ttf
    - family: Sarabun-Medium
      fonts:
        - asset: fonts/Sarabun-Medium.ttf

